# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Best eBook - eBooks Free Download Site
email: bestebookinfo@163.com
description: > # this means to ignore newlines until "baseurl:"
  Amazing Free eBook Download Site! Newest Free eBook Share! Free Download PDF, EPUB, MOBI eBooks. 10000+ IT eBooks Free Download! Maximum Speed! No Registration!
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.bestebook.info/" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: webjeda
copyright:
   name: webjeda
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 24
paginate_path: /page:num/

# Tracker
analytics: UA-55157705-2

# Comments
#disqus-shortname: bestebookinfo

#amazon tag
amazontag: bestebookinfo-20
stadlink: http://sh.st/st/4e4fa4d8c981e1ecd9a295281c605ced

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

